---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Jerusalem
      - PASSWORD=Burt2024$! #optional
        #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=Burt2024$! #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/home/assist/ #optional
    volumes:
      - /home/assist/:/home/assist/
    ports:
      - 8443:8443
    restart: unless-stopped
