server{
	listen 80;
	server_name _;
	root /srv;

	location /win {	
		#root /win;
		try_files $uri $uri/ /win/default;
		# Activate the next line if you want to list files
		 #autoindex on;
	}
	location /linux {
                #root /win;
                try_files $uri $uri/ /linux/default;
                # Activate the next line if you want to list files
                 #autoindex on;
        }
}
