#version: '3.3'
services:
    tailscale:
        container_name: tailscaled
        network_mode: host
        restart: unless-stopped
        security_opt:
            - label:disable
        volumes:
            - '/var/lib:/var/lib'
            - '/dev/net/tun:/dev/net/tun'
        cap_add:                  # Required for tailscale to work
            - NET_ADMIN
            - NET_RAW
        environment:
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_AUTHKEY=tskey-auth-??????
            - TS_ROUTES=192.168.32.0/24
        image: tailscale/tailscale
