version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_storage: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
      #volumes:
      #- /proc:/host/proc:ro
      #- /sys:/host/sys:ro
      #- /:/rootfs:ro
      #command:
      #- '--path.procfs=/host/proc'
      #- '--path.rootfs=/rootfs'
      #- '--path.sysfs=/host/sys'
      #- '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring
  modbus-exporter:
    image: shivi2021/modbus-exporter
    container_name: modbus-exporter
    restart: unless-stopped
    #expose:
      #- 9602
    ports:
      - "9602:9602"
    volumes:
      - ./:/app/config/
    command:
        #- ./modbus_exporter
      - '--config.file=/app/config/modbus.yml'
    networks:
      - monitoring
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk
    privileged: true
    expose:
      - 8080
    networks:
      - monitoring
  grafana-srv:
    image: grafana/grafana-enterprise
    container_name: grafana-srv
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
        #- '--web.console.libraries=/etc/prometheus/console_libraries'
        #- '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.size=50GB'
        #expose:
      #- 9090
    ports:
      - "9090:9090"
    networks:
      - monitoring
